const products = [
    {
        name: "iPhone 13 Pro",
        brand: "Apple",
        price: 1699,
        stock: 100,
        category: "Smartphones",
        colour: ["Alpine Green", "Silver", "Gold", "Graphite", "Sierra Blue"],
        details: [
            "6.1-inch Super Retina XDR display with ProMotion for a faster, more responsive feel",
            "Biggest Pro camera system upgrade ever for epic low-light shots and macro photography",
            "A15 Bionic with 5-core GPU — the fastest chip ever in a smartphone",
            "Ceramic Shield, tougher than any smartphone glass. And IP68 water resistance.",
            "5G for superfast downloads and high-quality streaming",
        ],
        thumbnail: "/iPhone_13_Pro/iPhone_13_Pro_1.png",
        images: [
            "/iPhone_13_Pro/iPhone_13_Pro_alpine_green.jpeg",
            "/iPhone_13_Pro/iPhone_13_Pro_silver.jpeg",
            "/iPhone_13_Pro/iPhone_13_Pro_gold.jpeg",
            "/iPhone_13_Pro/iPhone_13_Pro_graphite.jpeg",
            "/iPhone_13_Pro/iPhone_13_Pro_sierra_blue.jpeg",
        ],
        favourite: false,
    },
    {
        name: "iPhone 13",
        brand: "Apple",
        price: 1349,
        stock: 100,
        category: "Smartphones",
        colour: [
            "Green",
            "Pink",
            "Blue",
            "Midnight",
            "Starlight",
            "Product Red",
        ],
        details: [
            "6.1-inch Super Retina XDR display,footnote¹ now 28% brighter",
            "Our most advanced dual-camera system for incredible low-light photos and videos",
            "A15 Bionic with 4-core GPU - faster than the competition",
            "Ceramic Shield, tougher than any smartphone glass. And IP68 water resistance.",
            "5G for superfast downloads and high-quality streaming",
        ],
        thumbnail: "/iPhone_13/iPhone_13_thumbnail.jpeg",
        images: [
            "/iPhone_13/iPhone_13_green.jpeg",
            "/iPhone_13/iPhone_13_pink.jpeg",
            "/iPhone_13/iPhone_13_blue.jpeg",
            "/iPhone_13/iPhone_13_midnight.jpeg",
            "/iPhone_13/iPhone_13_starlight.jpeg",
            "/iPhone_13/iPhone_13_red.jpeg",
        ],
        favourite: false,
    },
    {
        name: "iPhone SE",
        brand: "Apple",
        price: 719,
        stock: 100,
        category: "Smartphones",
        colour: ["Midnight", "Starlight", "Product Red"],
        details: [
            "4.7-inch Retina HD display that's bright, colourful and sharp",
            "A15 Bionic, the same incredibly powerful chip that's in iPhone 13",
            "5G for fast downloads and high-quality streaming",
            "Smarter camera makes automatic adjustments, helping faces, places, everything look fabulous",
            "Home button with Touch ID — securely unlock, sign in to apps and use Apple Pay",
        ],
        thumbnail: "/iPhone_SE/iPhone_SE_thumbnail.jpeg",
        images: [
            "/iPhone_SE/iPhone_SE_midnight.jpeg",
            "/iPhone_SE/iPhone_SE_starlight.jpeg",
            "/iPhone_SE/iPhone_SE_red.jpeg",
        ],
        favourite: false,
    },
    {
        name: "iPhone 12",
        brand: "Apple",
        price: 999,
        stock: 100,
        category: "Smartphones",
        colour: ["Green", "Purple", "Blue", "White", "Black", "Product Red"],
        details: [
            "6.1-inch Super Retina XDR display for great contrast and incredible colour accuracy",
            "Advanced dual-camera system with Night mode and Dolby Vision HDR recording",
            "Super powerful A14 Bionic chip",
            "Ceramic Shield, tougher than any smartphone glass. And IP68 water resistance.",
            "5G for superfast downloads and high-quality streaming",
        ],
        thumbnail: "/iPhone_12/iPhone_12_thumbnail.jpeg",
        images: [
            "/iPhone_12/iPhone_12_green.jpeg",
            "/iPhone_12/iPhone_12_purple.jpeg",
            "/iPhone_12/iPhone_12_blue.jpeg",
            "/iPhone_12/iPhone_12_white.jpeg",
            "/iPhone_12/iPhone_12_black.jpeg",
            "/iPhone_12/iPhone_12_red.jpeg",
        ],
        favourite: false,
    },
    {
        name: "iPhone 11",
        brand: "Apple",
        price: 849,
        stock: 100,
        category: "Smartphones",
        colour: ["Green", "Purple", "White", "Yellow", "Black", "Product Red"],
        details: [
            "6.1-inch Liquid Retina HD display",
            "Dual-camera system with Night mode, Portrait mode, and 4K video up to 60 fps",
            "12MP TrueDepth front camera with Portrait mode, 4K video, and slo-mo",
            "A13 Bionic chip with Neural Engine",
            "Face ID for secure authentication and Apple Pay",
        ],
        thumbnail: "/iPhone_11/iPhone_11_thumbnail.jpeg",
        images: [
            "/iPhone_11/iPhone_11_green.jpeg",
            "/iPhone_11/iPhone_11_purple.jpeg",
            "/iPhone_11/iPhone_11_white.jpeg",
            "/iPhone_11/iPhone_11_yellow.jpeg",
            "/iPhone_11/iPhone_11_black.jpeg",
            "/iPhone_11/iPhone_11_red.jpeg",
        ],
        favourite: false,
    },
];
export default products;
